config/routes.rb
Rails.application.routes.draw do
  resources :nginxtests
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/nginxtest.rb
class Nginxtest < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/nginxtests_controller.rb
class NginxtestsController < ApplicationController
  before_action :set_nginxtest, only: %i[ show edit update destroy ]

  # GET /nginxtests or /nginxtests.json
  def index
    @nginxtests = Nginxtest.all
  end

  # GET /nginxtests/1 or /nginxtests/1.json
  def show
  end

  # GET /nginxtests/new
  def new
    @nginxtest = Nginxtest.new
  end

  # GET /nginxtests/1/edit
  def edit
  end

  # POST /nginxtests or /nginxtests.json
  def create
    @nginxtest = Nginxtest.new(nginxtest_params)

    respond_to do |format|
      if @nginxtest.save
        format.html { redirect_to @nginxtest, notice: "Nginxtest was successfully created." }
        format.json { render :show, status: :created, location: @nginxtest }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @nginxtest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /nginxtests/1 or /nginxtests/1.json
  def update
    respond_to do |format|
      if @nginxtest.update(nginxtest_params)
        format.html { redirect_to @nginxtest, notice: "Nginxtest was successfully updated." }
        format.json { render :show, status: :ok, location: @nginxtest }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @nginxtest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nginxtests/1 or /nginxtests/1.json
  def destroy
    @nginxtest.destroy
    respond_to do |format|
      format.html { redirect_to nginxtests_url, notice: "Nginxtest was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_nginxtest
      @nginxtest = Nginxtest.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def nginxtest_params
      params.require(:nginxtest).permit(:title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/nginxtests_helper.rb
module NginxtestsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nginx</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/nginxtests/_form.html.erb
<%= form_with(model: nginxtest, local: true) do |form| %>
  <% if nginxtest.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(nginxtest.errors.count, "error") %> prohibited this nginxtest from being saved:</h2>

      <ul>
      <% nginxtest.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/nginxtests/edit.html.erb
<h1>Editing Nginxtest</h1>

<%= render 'form', nginxtest: @nginxtest %>

<%= link_to 'Show', @nginxtest %> |
<%= link_to 'Back', nginxtests_path %>

app/views/nginxtests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Nginxtests</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @nginxtests.each do |nginxtest| %>
      <tr>
        <td><%= nginxtest.title %></td>
        <td><%= nginxtest.content %></td>
        <td><%= link_to 'Show', nginxtest %></td>
        <td><%= link_to 'Edit', edit_nginxtest_path(nginxtest) %></td>
        <td><%= link_to 'Destroy', nginxtest, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Nginxtest', new_nginxtest_path %>

app/views/nginxtests/new.html.erb
<h1>New Nginxtest</h1>

<%= render 'form', nginxtest: @nginxtest %>

<%= link_to 'Back', nginxtests_path %>

app/views/nginxtests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @nginxtest.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @nginxtest.content %>
</p>

<%= link_to 'Edit', edit_nginxtest_path(@nginxtest) %> |
<%= link_to 'Back', nginxtests_path %>